### ISSUE TITLE
Removing links and Word and LibreOffice Writer TOC link annotations

### ISSUE THREAD

**Issue by sh511** [mkl-public/testarea-itext7#5]
I am been using the code from testRemoveLinksBySubclass() to remove URI links from PDF files created from MS Word (365) or LibreOffice. I got exceptions related to "empty action" in the annotations associated with the TOC. I examined the PDF files with RUPS and did confirm that the TOC had annotations of subtype Link but no /A thus generating an exception while trying to use  the action retrieved with getAction(). I needed to add a test for a null action.

The PDF TOC created by Word and LO Writer also differs as Word creates additional /Annot type, /Link subtype ditionaries for /Border but these have a ?a -> /S : /GoTo and are not problematic. LO does not generate those additional annotations.

While the null test works for me, I wanted to document the issue.

**Comment by mkl-public** [comment]
Thanks for the hint, I added a `null` test there, too.
